### ISSUE TITLE
Make repo attractive.

### ISSUE THREAD

**Issue by swapniltri** [swapniltri/MYproject#1]
You can add JS file.
or can modify HTML and CSS file.

**Comment by Utsav-Ladani** [comment]
I want to make it attractive. Can I go ahead?

**Comment by omen65** [comment]
i will help add some improvement

**Comment by hariomkushwaha** [comment]
I want to contribute to this

**Comment by swapniltri** [comment]
@Utsav-Ladani yaa go for it.

**Comment by Utsav-Ladani** [comment]
Thanks @swapniltri

**Comment by Utsav-Ladani** [comment]
Hello @swapniltri , Review PR and merge

**Comment by Utsav-Ladani** [comment]
#7 Improve UI

**Comment by KeerthanaHK** [comment]
Can I work on this? I would like to add a readme file containing the description. Also would like to improve UI. @swapniltri
